"""API v1 package.

Routers are imported explicitly by ``app.main``. Keep this package initializer
lightweight so importing one router does not import the entire application.
"""

__all__ = [
    "advanced_analytics",
    "advanced_intelligence",
    "agents",
    "analytics",
    "auth",
    "awards",
    "boq",
    "canonical",
    "capacity_risk",
    "chat",
    "communication",
    "competitors",
    "contractor_intelligence",
    "contractors",
    "crawl",
    "crawler",
    "dashboard",
    "deptree",
    "embeddings",
    "epw3",
    "escalation",
    "executive",
    "government_portals",
    "graph",
    "intelligence",
    "market_index",
    "monitoring",
    "payments",
    "ppr2025",
    "predictions",
    "pricing",
    "rate_analysis",
    "reports",
    "search",
    "sor",
    "system",
    "tender_docs",
    "tender_matching",
    "tender_processing",
    "tenders",
    "validation",
    "webhooks",
]
