declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'

  interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: number | string
    absoluteStrokeWidth?: boolean
  }

  export type Icon = FC<LucideProps>
  export type LucideIcon = Icon

  export const Menu: Icon
  export const X: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const ChevronDown: Icon
  export const ChevronUp: Icon
  export const Search: Icon
  export const Bell: Icon
  export const Settings: Icon
  export const User: Icon
  export const LogOut: Icon
  export const Home: Icon
  export const TrendingUp: Icon
  export const FileText: Icon
  export const Shield: Icon
  export const ShieldCheck: Icon
  export const BookOpen: Icon
  export const Building: Icon
  export const Building2: Icon
  export const LayoutDashboard: Icon
  export const Activity: Icon
  export const AlertTriangle: Icon
  export const CheckCircle: Icon
  export const Clock: Icon
  export const Download: Icon
  export const Upload: Icon
  export const RefreshCw: Icon
  export const MoreHorizontal: Icon
  export const Plus: Icon
  export const Minus: Icon
  export const ArrowUp: Icon
  export const ArrowDown: Icon
  export const Info: Icon
  export const Loader2: Icon
  export const ExternalLink: Icon
  export const Filter: Icon
  export const Globe: Icon
  export const Target: Icon
  export const BarChart3: Icon
  export const PieChart: Icon
  export const LineChart: Icon
  export const Bot: Icon
  export const Sparkles: Icon
  export const Brain: Icon
  export const Lightbulb: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const ThumbsUp: Icon
  export const ThumbsDown: Icon
  export const Star: Icon
  export const Trash2: Icon
  export const Edit3: Icon
  export const Copy: Icon
  export const Share2: Icon
  export const Maximize2: Icon
  export const Minimize2: Icon
  export const GripVertical: Icon
  export const PanelLeftClose: Icon
  export const PanelLeftOpen: Icon
  export const PanelRightClose: Icon
  export const PanelRightOpen: Icon
  export const Columns: Icon
  export const LayoutGrid: Icon
  export const List: Icon
  export const Check: Icon
  export const Circle: Icon
  export const Square: Icon
  export const SlidersHorizontal: Icon
  export const HelpCircle: Icon
  export const Database: Icon
  export const Lock: Icon
  export const Unlock: Icon
  export const Key: Icon
  export const DollarSign: Icon
  export const Percent: Icon
  export const Calendar: Icon
  export const Clock4: Icon
  export const Timer: Icon
  export const Users: Icon
  export const UserPlus: Icon
  export const UserCheck: Icon
  export const Mail: Icon
  export const Phone: Icon
  export const MapPin: Icon
  export const Link: Icon
  export const Paperclip: Icon
  export const Image: Icon
  export const ClipboardList: Icon
  export const ClipboardCheck: Icon
  export const BadgeCheck: Icon
  export const BadgeAlert: Icon
  export const BadgeInfo: Icon
  export const Award: Icon
  export const Trophy: Icon
  export const Medal: Icon
  export const Handshake: Icon
  export const Scale: Icon
  export const Hammer: Icon
  export const Wrench: Icon
  export const HardHat: Icon
  export const Ruler: Icon
  export const Compass: Icon
  export const Layers: Icon
  export const GitBranch: Icon
  export const Zap: Icon
  export const Flame: Icon
  export const Sun: Icon
  export const Moon: Icon
  export const Monitor: Icon
  export const Palette: Icon
  export const Contrast: Icon
  export const ZoomIn: Icon
  export const ZoomOut: Icon
  export const Maximize: Icon
  export const Minimize: Icon
  export const History: Icon
  export const RefreshCcw: Icon
  export const RotateCw: Icon
  export const RotateCcw: Icon
  export const ArrowLeft: Icon
  export const ArrowRight: Icon
  export const Send: Icon
  export const MessageSquare: Icon
  export const Bookmark: Icon
  export const Book: Icon
  export const Library: Icon
  export const Folder: Icon
  export const FolderOpen: Icon
  export const File: Icon
  export const FilePlus: Icon
  export const FileEdit: Icon
  export const FileSearch: Icon
  export const Package: Icon
  export const Box: Icon
  export const Server: Icon
  export const Cloud: Icon
  export const Wifi: Icon
  export const WifiOff: Icon
  export const Smartphone: Icon
  export const Tablet: Icon
  export const Laptop: Icon
  export const Play: Icon
  export const Pause: Icon
  export const Mic: Icon
  export const Gauge: Icon
  export const Thermometer: Icon
  export const ArrowUpDown: Icon
  export const CreditCard: Icon
  export const Wallet: Icon
  export const Landmark: Icon
  export const ChartBar: Icon
  export const ChartLine: Icon
  export const ChartPie: Icon
  export const ChartArea: Icon
  export const ChartColumn: Icon
  export const Radar: Icon
  export const TrendingDown: Icon
  export const ListChecks: Icon
  export const Radio: Icon
  export const XCircle: Icon
  export const AlertCircle: Icon
  export const Briefcase: Icon
}
